mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

spring:
  application:
    name: zuul-gateway
  jackson:
      serialization:
        INDENT_OUTPUT: true
  datasource:
      name: spring_security
      url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&characterEncoding=utf8
      username: root
      password: adminadmin
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 2333

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/
zuul:
  routes:
    company-api:
      serviceId: company-api
      path: /**
    personal-api:
      serviceId: personal-api
      path: /**
    token-generator:
      serviceId: token-manager
      path: /**

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

