spring:
  application:
    name: digital-sign-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpringForAll/spring-cloud-digital-sign/
          search-paths: config

server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/

